-- 1. 커스텀 ENUM 타입 생성
CREATE TYPE public.permission_type AS ENUM (
  'TRIAL', -- 회원가입시 기본 제공되는 무료 체험
  'PAID'   -- 유료 결제 플랜
);
COMMENT ON TYPE public.permission_type IS '권한의 종류를 나타내는 ENUM 타입입니다.';

-- 2. workflows 테이블 생성
CREATE TABLE public.workflows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  workflow_json jsonb NOT NULL,
  CONSTRAINT workflows_pkey PRIMARY KEY (id)
);

-- 3. permissions 테이블 생성 (type 컬럼 적용)
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  type public.permission_type NOT NULL,
  duration_seconds integer NOT NULL,
  workflow_id uuid NOT NULL,
  CONSTRAINT permissions_pkey PRIMARY KEY (id),
  CONSTRAINT permissions_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES public.workflows(id) ON DELETE CASCADE
);
COMMENT ON COLUMN public.permissions.type IS '권한의 타입을 나타냅니다 (TRIAL, PAID 등).';

-- 4. user_permissions 테이블 생성
CREATE TABLE public.user_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  expires_at timestamptz NOT NULL,
  CONSTRAINT user_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT user_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT user_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id) ON DELETE CASCADE
);

-- 5. seed data workflows
INSERT INTO public.workflows (name, workflow_json)
VALUES (
  'KREAM 판매내역',
  '"{\"site_name\":\"KREAM\",\"steps\":[{\"step_name\":\"사용자로그인\",\"action_type\":\"manual_login\",\"target_url\":\"https://kream.co.kr/login\",\"success_condition\":{\"type\":\"element_visible\",\"selector\":\"a.top_link\",\"text_contains\":\"로그아웃\",\"timeout\":120}},{\"step_name\":\"일반판매정산내역수집\",\"action_type\":\"kream_scrap_1\",\"target_url\":\"https://kream.co.kr/my/selling?tab=finished&status=payout_completed\",\"output_filename\":\"크림_일반판매\",\"list_item_selector\":\"a.product_list_info_action\",\"list_date_selector\":\".caption_itemp\",\"detail_page_rules\":{\"order_number\":{\"column_name\":\"주문번호\",\"selector\":\".text-header-checkoutp\",\"type\":\"text\"},\"product_name_eng\":{\"column_name\":\"상품명(영문)\",\"selector\":\"p.product_title\",\"type\":\"text\"},\"product_name_kor\":{\"column_name\":\"상품명(한글)\",\"selector\":\"p.product_subtitle\",\"type\":\"text\"},\"product_model\":{\"column_name\":\"상품모델\",\"selector\":\"p.product_description\",\"type\":\"text\"},\"size\":{\"column_name\":\"사이즈\",\"selector\":\"span.product_option--name\",\"type\":\"text\"},\"transaction_date\":{\"column_name\":\"거래일시\",\"label\":\"거래일시\",\"type\":\"find_by_label\"},\"payout_date\":{\"column_name\":\"정산일\",\"label\":\"정산일\",\"type\":\"find_by_label\"},\"instant_sell_price\":{\"column_name\":\"즉시판매가\",\"label\":\"즉시판매가\",\"type\":\"find_by_label\"},\"commission_fee\":{\"column_name\":\"수수료\",\"label\":\"수수료\",\"type\":\"find_by_label\"},\"payout_amount\":{\"column_name\":\"정산금액\",\"label\":\"정산금액\",\"type\":\"find_by_label\"}}},{\"step_name\":\"보관판매정산내역수집\",\"action_type\":\"kream_scrap_2\",\"target_url\":\"https://kream.co.kr/my/inventory?tab=finished&status=payout_completed\",\"output_filename\":\"크림_보관판매\",\"list_item_selector\":\".inventory_item\",\"list_date_selector\":\".tab_item.date.value\",\"detail_button_selector\":\".btn.detail\",\"drawer_selector\":\".drawer__content\",\"drawer_close_button_selector\":\".btn_layer_close\",\"detail_rules\":{\"order_number\":{\"column_name\":\"주문번호\",\"selector\":\".inventory_product.inventory_number\",\"type\":\"text\"},\"product_name_eng\":{\"column_name\":\"상품명(영문)\",\"selector\":\".inventory_product.name\",\"type\":\"text\"},\"product_model\":{\"column_name\":\"상품모델\",\"selector\":\"p.codespan.code_text\",\"type\":\"text\"},\"size\":{\"column_name\":\"사이즈\",\"selector\":\".inventory_product.size_text\",\"type\":\"text\"},\"transaction_date\":{\"column_name\":\"거래일시\",\"label\":\"거래일시\",\"type\":\"find_by_label_v2\"},\"payout_date\":{\"column_name\":\"정산일\",\"selector\":\".status_bar_info.info_desc\",\"type\":\"text\"},\"instant_sell_price\":{\"column_name\":\"즉시판매가\",\"label\":\"판매가\",\"type\":\"find_by_label_v2\"},\"commission_fee\":{\"column_name\":\"수수료\",\"label\":\"수수료\",\"type\":\"find_by_label_v2\"},\"payout_amount\":{\"column_name\":\"정산금액\",\"label\":\"정산금액\",\"type\":\"find_by_label_v2\"}}}]}"'
)
RETURNING id;

-- 6. seed data permissions
INSERT INTO public.permissions (name, type, duration_seconds, workflow_id)
VALUES (
  'KREAM 1시간 무료 체험',
  'TRIAL',
  3600,
  'fd8c3853-73e4-43c3-bee4-74fbeb49dfb3'
);

-- 7. 새로운 사용자가 추가될 때 실행될 함수를 생성합니다.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  trial_permission_id uuid;
  trial_duration_seconds int;
BEGIN
  -- permissions 테이블에서 type이 'TRIAL'인 권한의 ID와 기간을 찾습니다.
  SELECT id, duration_seconds INTO trial_permission_id, trial_duration_seconds
  FROM public.permissions
  WHERE type = 'TRIAL'
  LIMIT 1;

  -- 'TRIAL' 권한이 존재할 경우에만 실행합니다.
  IF trial_permission_id IS NOT NULL THEN
    -- user_permissions 테이블에 새로운 사용자의 무료 체험 권한을 추가합니다.
    INSERT INTO public.user_permissions (user_id, permission_id, expires_at)
    VALUES (
      NEW.id, -- 방금 가입한 사용자의 ID
      trial_permission_id, -- 위에서 찾은 TRIAL 권한의 ID
      now() + (trial_duration_seconds * interval '1 second') -- 현재시간 + 권한의 유효시간
    );
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 8. auth.users 테이블에 새로운 사용자가 추가될 때마다 위 함수를 실행하는 트리거를 생성합니다.
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();